### ISSUE TITLE
Upstream changes?

### ISSUE THREAD

**Issue by slotThe** [psibi/rustic#15]
Hey psibi,

do you have any plans on upstreaming these changes? (AFAIK you have a commit bit on https://github.com/brotzeit/rustic right?)

On another note, would it be worth it to transfer the repository to `rust-lang`, much like `rust-mode` already it?

**Comment by psibi** [comment]
@slotThe Sorry for the late reply, I missed this issue.

> do you have any plans on upstreaming these changes? (AFAIK you have a commit bit on https://github.com/brotzeit/rustic right?)

Yes, unfortunately the situation is slightly complicated. While I can merge other's PR, I cannot merged my own PR. And I have not been able to reach @brotzeit, I hope he is doing okay. I did send a mail to him couple of months ago and didn't hear back from him.

> On another note, would it be worth it to transfer the repository to rust-lang, much like rust-mode already it?

Yes, if possible. But I don't know where to start. Do you know what is the procedure ?

**Comment by slotThe** [comment]
> Yes, unfortunately the situation is slightly complicated. While I can merge other's PR, I cannot merged my own PR. And I have not been able to reach @brotzeit, I hope he is doing okay. I did send a mail to him couple of months ago and didn't hear back from him.

Ah, that explains the situation.

> > On another note, would it be worth it to transfer the repository to rust-lang, much like rust-mode already it?
>
> Yes, if possible. But I don't know where to start. Do you know what is the procedure ?

I do not—I saw you around the `rust-mode` repo, so I figured that you might :) I can ask around on the Rust discourse (which I guess is the place to ask that kind of stuff) if you want

**Comment by psibi** [comment]
> I can ask around on the Rust discourse (which I guess is the place to ask that kind of stuff) if you want

Yeah, that would be helpful. Thanks!

**Comment by slotThe** [comment]
https://users.rust-lang.org/t/process-to-add-a-repository-to-rust-lang/109149

I guess no one knows… :)

**Comment by psibi** [comment]
Ah, okay. Thanks for asking it in the rust forum. :-)

**Comment by psibi** [comment]
@slotThe We have a new home for rustic: https://github.com/emacs-rustic/rustic  More details here: https://psibi.in/posts/rustic.html

Probably this issue can be closed now ? :-)

**Comment by slotThe** [comment]
Oh, that's a great development! Thanks for keeping me updated, this can then indeed be closed
